[project]
name = "willow-cpp-sdk"
version = "5.2.8"
description = "Willow 5 Runtime: C++ Edge SDK for Zero-Shot Action Recognition"
authors = ["Willow Dynamics <engineering@willowdynamics.com>"]
license = "MIT"
homepage = "https://github.com/Willow-Dynamics/willow-cpp-sdk"
repository = "https://github.com/Willow-Dynamics/willow-cpp-sdk.git"
keywords =["computer-vision", "biomechanics", "dtw", "edge", "robotics", "cpp"]

[build]
system = "cmake"
requires = ["cmake>=3.14"]

[dependencies]
# Optional dependencies required for the Client provisioning module
libcurl = { version = "*", optional = true }